### ISSUE TITLE
老哥 你也是thinkpad s2: i5-6200的吗

### ISSUE THREAD

**Issue by xzyc** [yxze/thinkpad-s2-2016#1]
谢谢你的分享！

**Comment by yxze** [comment]
我没在这号上面更新了，而在这上面更新https://github.com/Dark-a-captain/Tinkpad-s2-2016

**Comment by yxze** [comment]
> 谢谢你的分享！
我没在这号上面更新了，而在这上面更新https://github.com/Dark-a-captain/Tinkpad-s2-2016
